### ISSUE TITLE
Including display id fails

### ISSUE THREAD

**Issue by varac** [fd0/grobi#17]
These displays are detected by grobi:

```
--- ~ » grobi show                                                                                                                
LVDS-1     LGD-728-0
HDMI-1     SAM-2537-1515804490
```

I use this config:

```
  - name: blah                                                                                                                                     
    outputs_connected: [LVDS-1, HDMI-1-SAM-2537-1515804490]                                                                                          
    primary: HDMI-1-SAM-2537-1515804490                                                                                                              
    configure_row:                                                                                                                                   
      - LVDS-1                                                                                                                                       
      - HDMI-1-SAM-2537-1515804490      
```

But grobi fails to update the displays:

```
--- ~ » grobi  update                                            
warning: output HDMI-1-SAM-2537-1515804490 not found; ignoring
```
