### ISSUE TITLE
Unknown state. grobi exists

### ISSUE THREAD

**Issue by infabo** [fd0/grobi#25]
```
Dez 06 08:24:40 NOTEBOOK023 sh[2189]: grobi: 08:24:40.868321 reading config from /home/inf/.config/grobi.conf
Dez 06 08:24:40 NOTEBOOK023 sh[2189]: grobi: 08:24:40.869037 grobi 0.5.1 (v0.5.1-19-gdaa886b), compiled with go1.12.7 on linux
Dez 06 08:24:40 NOTEBOOK023 sh[2189]: grobi: 08:24:40.869068 successfully subscribed to X RANDR change events
Dez 06 08:24:40 NOTEBOOK023 sh[2189]: unknown state "unknown"
```

```
$ xrandr
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
eDP1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 290mm x 170mm
   1920x1080     59.93*+  59.93  
   1680x1050     59.88  
   1400x1050     59.98  
   1600x900      60.00    59.95    59.82  
   1280x1024     60.02  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1368x768      60.00    59.88    59.85  
   1280x800      59.81    59.91  
   1280x720      59.86    60.00    59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   640x360       59.84    59.32    60.00  
DP1 disconnected (normal left inverted right x axis y axis)
DP1-1 unknown connection (normal left inverted right x axis y axis)
   1368x768      59.88  
   1280x800      59.81  
   1280x720      59.86  
   1024x768      60.00  
   1024x576      59.90  
   960x540       59.63  
   800x600       60.32  
   640x480       59.94  
DP1-2 unknown connection primary (normal left inverted right x axis y axis)
   1368x768      59.88  
   1280x800      59.81  
   1280x720      59.86  
   1024x768      60.00  
   1024x576      59.90  
   960x540       59.63  
   800x600       60.32  
   640x480       59.94  
DP2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

```
cat ~/.config/grobi.conf
# vim:ft=yaml

rules:
  - name: Display Extender
    # grobi takes the list of all the
    # outputs xrandr returns and verifies that HDMI2 and HDMI3 are connected, and
    # DP2-2 is present (but may be disconnected).
    outputs_connected: [eDP1, DP1-1, DP1-2]
    outputs_present: [DP1-1, DP1-2]

    # when this rule matches, HDMI2 and HDMI3 are activated in their default
    # resolution and set besides each other in a typical dual-monitor
    # configuration: left is HDMI2, right is HDMI3
    configure_row:
#        - eDP1
        - DP1-1
        - DP1-2

    # atomic instructs grobi to only call xrandr once and configure all the
    # outputs. This does not always work with all graphic cards.
    atomic: false

    # For the output HDMI3, the flag --primary will be added to the xrandr
    # call, so that e.g. the tray icons are displayed on this monitor (requires
    # the window manager to do this).
    primary: DP1-2

    # Additional commands can be specified per rule, in this case we make sure
    # that xautolock is enabled and locks the screen after a while.
#   execute_after:
#     - python3 /usr/share/xfpanel-switch/xfpanel-switch/panelconfig.py load /home/inf/.local/share/xfpanel-switch/displaylink.tar.bz2

  # This is a rule for mobile computing, i.e. outside of the docking station defined above.
  - name: Mobile

    # In order to match, the outputs HDMI2 and HDMI3 may be present, but must be disconnected.
    outputs_disconnected:
      - DP1-1
      - DP1-2

    # Here, only the internal LCD panel is activated.
    configure_single: eDP1

#   execute_after:
#     - python3 /usr/share/xfpanel-switch/xfpanel-switch/panelconfig.py load /home/inf/.local/share/xfpanel-switch/laptop.tar.bz2

  - name: Fallback
    configure_single: eDP1
```
