### ISSUE TITLE
Why does grobi turn off outputs?

### ISSUE THREAD

**Issue by stapelberg** [fd0/grobi#26]
I’m trying to use grobi to automatically run `xrandr` whenever I re-plug my monitor, which is required sometimes (*sigh*) for my monitor to sync with my GPU.

While using dry-run mode, I got this sequence of commands which grobi would have run:
```
% grobi watch --dry-run                             
xrandr --output DP-0 --auto --output DP-4 --auto --right-of DP-0
# <unplug monitor cables>
xrandr --output DP-0 --off --output DP-4 --off
xrandr --output DP-0 --off --output DP-4 --off
# <replug monitor cables>
xrandr --output DP-0 --auto --output DP-4 --auto --right-of DP-0
```

The first and last command are what I want it to run, but I don’t want it to turn off outputs. Turning off the output results in i3 re-arranging workspaces, which I don’t want in this scenario (I’m removing *all* outputs).

I had a brief look around, but couldn’t find any option to stop grobi from disabling outputs. Did I miss anything? Is there some rationale behind this behavior, or could an option be added to not turn off outputs?

In case it’s relevant, my grobi.conf reads:
```
# vim:ft=yaml

rules:
  - name: UP3218K
    outputs_connected: [DP-0, DP-4]
    configure_row:
        - DP-0
        - DP-4
    atomic: true
```

Thanks,
