### ISSUE TITLE
Set refresh rate?

### ISSUE THREAD

**Issue by jonaz** [fd0/grobi#29]
Now i had to use this hack: 
```
  - name: Dockhome
    outputs_connected: 
      - eDP-1
      - DP-2-1
      - DP-2-8-LEN-25065*
    configure_row:
        - eDP-1
        - DP-2-1@1920x1080 #hack since we cannot set hz in grobi
        - DP-2-8
    atomic: true
    execute_after:
      - "xrandr --output DP-2-1 --mode 2560x1440 --rate 60 --right-of eDP-1 --output DP-2-8 --right-of DP-2-1" #hack to set refreshrate
```

I have 2 suggestions. 

1
Implement `DP-2-1@1920x1080@60` and then we just change the SplitN to be 3 and take the last one as --rate. 

2
Implement environment variables that is sent to execute_after. Then we can add for example GROBI_ROW_1=eDP-1 , GROBI_ROW_1=DP-2-1 , GROBI_ROW_3=DP-2-8

The execute_after could then look like this:
```
      - "xrandr --output $GROBI_ROW_2 --mode 2560x1440 --rate 60 --right-of $GROBI_ROW_1 --output $GROBI_ROW_3 --right-of $GROBI_ROW_2"
```

Then we can always customize our xrandr in the execute_after. Which means stuff like i saw discussed in #8  like --pos can also be solved like this.
